"""
SAT_BASIL — ML hyperparameter tuning (v2: SNV + cluster augmentation)
======================================================================
- Sensor × Scope × Data × Norm × Model
  - sensor: vn, sw
  - scope : all_leaf, c0, c1, c2
  - data  : raw, ae, gan
  - norm  : none, snv
  - model : RandomForest, SVM, XGBoost, KNN
- Total combos: 2 × 4 × 3 × 2 × 4 = 192
- Tuning: Optuna 200 trials × 5-fold CV, TPE + MedianPruner
- Pipeline: load → (SNV optional) → StandardScaler → model
- Storage : Optuna SQLite + best_params.json + master_results.csv

Notes:
- Per-cluster (c0/c1/c2) splits are produced by
  preprocessing/make_per_cluster_csvs.py and written to data/per_cluster_split/.
  scope=all_leaf can be reproduced directly from data/train_test_split/.
- Augmentation CSVs live in data/augmentation/ (ae|gan)_{swir,vnir}_n300.csv.
  Pass --aug_root only if you placed augmented files elsewhere.
"""
import argparse
import json
import time
from datetime import datetime
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import optuna
import seaborn as sns
from optuna.pruners import MedianPruner
from optuna.samplers import TPESampler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    auc,
    confusion_matrix,
    f1_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler, label_binarize
from sklearn.svm import SVC
from xgboost import XGBClassifier

# ============================================================
# Config
# ============================================================
REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data"
SPLIT_DIR = DATA / "train_test_split"          # all_leaf uses these
CLUSTER_SPLIT_DIR = DATA / "per_cluster_split"  # c0/c1/c2 generated by preprocessing/
AUG_DIR_DEFAULT = DATA / "augmentation"

SENSOR_LONG = {"sw": "swir", "vn": "vnir"}

N_TRIALS = 200
N_SPLITS = 5
RANDOM_STATE = 42

SENSORS = ["vn", "sw"]
SCOPES = ["all_leaf", "c0", "c1", "c2"]
DATAS = ["raw", "ae", "gan"]
NORMS = ["none", "snv", "msc"]
MODELS = ["RandomForest", "SVM", "XGBoost", "KNN"]


# ============================================================
# Preprocessing: SNV / MSC
# ============================================================
def apply_snv(X: np.ndarray) -> np.ndarray:
    """Standard Normal Variate (sample-wise): 각 row → (row - mean) / std."""
    X = np.asarray(X, dtype=np.float64)
    m = X.mean(axis=1, keepdims=True)
    s = X.std(axis=1, keepdims=True)
    s = np.where(s < 1e-12, 1.0, s)
    return (X - m) / s


def apply_msc(X: np.ndarray, reference: np.ndarray = None):
    """Multiplicative Scatter Correction.
    Returns (X_msc, reference). If reference is None, uses mean of input (train fit).
    """
    X = np.asarray(X, dtype=np.float64)
    if reference is None:
        reference = X.mean(axis=0)
    out = np.zeros_like(X)
    for i in range(X.shape[0]):
        a, b = np.polyfit(reference, X[i], 1)
        if abs(a) < 1e-10:
            out[i] = X[i] - b
        else:
            out[i] = (X[i] - b) / a
    return out, reference


# ============================================================
# Data loaders
# ============================================================
def find_aug_csv(aug_root: Path, sensor: str, scope: str, data: str) -> Path:
    """Locate augmentation CSV. Default layout: aug_root/{ae|gan}_{swir,vnir}_n300.csv.
    Per-scope variants (aug_root/{sensor}/{scope}/...) are also supported."""
    s_long = SENSOR_LONG[sensor]
    if data == "ae":
        fname = f"ae_{s_long}_n300.csv"
    elif data == "gan":
        fname = f"gan_{s_long}_n300.csv"
    else:
        raise ValueError(data)

    # Per-scope structure (if produced separately)
    scoped = aug_root / sensor / scope / fname
    if scoped.exists():
        return scoped
    # Flat default layout
    flat = aug_root / fname
    if flat.exists() and scope == "all_leaf":
        return flat
    raise FileNotFoundError(f"augmentation CSV not found: {scoped} (or fallback {flat})")


def load_train_test(scope: str, sensor: str, data: str, aug_root: Path):
    """Return (X_train, y_train, X_test, y_test) for the given combo."""
    s_long = SENSOR_LONG[sensor]
    if scope == "all_leaf":
        train_path = SPLIT_DIR / f"train_{s_long}.csv"
        test_path = SPLIT_DIR / f"test_{s_long}.csv"
    else:  # c0 / c1 / c2 (requires preprocessing/make_per_cluster_csvs.py)
        train_path = CLUSTER_SPLIT_DIR / f"{scope}_train_{s_long}.csv"
        test_path = CLUSTER_SPLIT_DIR / f"{scope}_test_{s_long}.csv"

    test_df = pd.read_csv(test_path)
    if data == "raw":
        train_df = pd.read_csv(train_path)
    else:
        train_df = pd.read_csv(find_aug_csv(aug_root, sensor, scope, data))

    # feat_* 컬럼만 X 로
    feat_cols = [c for c in train_df.columns if c.startswith("feat_")]
    X_train = train_df[feat_cols].values
    y_train = train_df["label"].values

    feat_cols_te = [c for c in test_df.columns if c.startswith("feat_")]
    X_test = test_df[feat_cols_te].values
    y_test = test_df["label"].values

    return X_train, y_train, X_test, y_test


# ============================================================
# Extended hyperparameter search spaces
# ============================================================
def build_model(model_name: str, trial):
    if model_name == "RandomForest":
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 50, 500),
            "max_depth": trial.suggest_int("max_depth", 3, 30),
            "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
            "max_features": trial.suggest_categorical(
                "max_features", ["sqrt", "log2", None]),
            "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
            "class_weight": trial.suggest_categorical(
                "class_weight", ["balanced", "balanced_subsample", None]),
            "random_state": RANDOM_STATE,
            "n_jobs": -1,
        }
        return RandomForestClassifier(**params), params

    if model_name == "SVM":
        kernel = trial.suggest_categorical("kernel", ["rbf", "linear", "poly", "sigmoid"])
        params = {
            "C": trial.suggest_float("C", 1e-2, 1e2, log=True),
            "gamma": trial.suggest_float("gamma", 1e-4, 1e1, log=True),
            "kernel": kernel,
            "class_weight": trial.suggest_categorical("class_weight", ["balanced", None]),
            "probability": True,
            "random_state": RANDOM_STATE,
            "max_iter": 5000,
        }
        if kernel in ("poly", "sigmoid"):
            params["coef0"] = trial.suggest_float("coef0", 0.0, 1.0)
        if kernel == "poly":
            params["degree"] = trial.suggest_int("degree", 2, 5)
        return SVC(**params), params

    if model_name == "XGBoost":
        params = {
            "max_depth": trial.suggest_int("max_depth", 3, 15),
            "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.5, log=True),
            "n_estimators": trial.suggest_int("n_estimators", 50, 500),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 10.0),
            "reg_lambda": trial.suggest_float("reg_lambda", 0.0, 10.0),
            "eval_metric": "mlogloss",
            "random_state": RANDOM_STATE,
            "n_jobs": -1,
            "use_label_encoder": False,
        }
        return XGBClassifier(**params), params

    if model_name == "KNN":
        params = {
            "n_neighbors": trial.suggest_int("n_neighbors", 1, 50),
            "weights": trial.suggest_categorical("weights", ["uniform", "distance"]),
            "p": trial.suggest_int("p", 1, 3),
            "algorithm": trial.suggest_categorical(
                "algorithm", ["auto", "ball_tree", "kd_tree", "brute"]),
            "leaf_size": trial.suggest_int("leaf_size", 10, 50),
            "n_jobs": -1,
        }
        return KNeighborsClassifier(**params), params

    raise ValueError(f"Unknown model: {model_name}")


def build_final_model(model_name: str, best_params: dict):
    p = dict(best_params)
    if model_name == "RandomForest":
        p["random_state"] = RANDOM_STATE
        p["n_jobs"] = -1
        return RandomForestClassifier(**p)
    if model_name == "SVM":
        p["probability"] = True
        p["random_state"] = RANDOM_STATE
        p.setdefault("max_iter", 5000)
        return SVC(**p)
    if model_name == "XGBoost":
        p["eval_metric"] = "mlogloss"
        p["random_state"] = RANDOM_STATE
        p["n_jobs"] = -1
        p["use_label_encoder"] = False
        return XGBClassifier(**p)
    if model_name == "KNN":
        p["n_jobs"] = -1
        return KNeighborsClassifier(**p)
    raise ValueError(f"Unknown model: {model_name}")


# ============================================================
# Optuna objective with CV
# ============================================================
def objective(trial, X, y, model_name):
    _, params = build_model(model_name, trial)
    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
    accs = []
    for fold_i, (tr_idx, va_idx) in enumerate(skf.split(X, y)):
        model = build_final_model(model_name, params)
        model.fit(X[tr_idx], y[tr_idx])
        preds = model.predict(X[va_idx])
        accs.append(accuracy_score(y[va_idx], preds))
        trial.report(float(np.mean(accs)), step=fold_i)
        if trial.should_prune():
            raise optuna.TrialPruned()
    return float(np.mean(accs))


# ============================================================
# Plot helpers
# ============================================================
def save_confusion(y_true, y_pred, class_names, out_path, title):
    cm = confusion_matrix(y_true, y_pred, normalize="true")
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt=".2f", cmap="Blues",
                xticklabels=class_names, yticklabels=class_names)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()


def save_roc(y_bin, y_prob, class_names, out_path, title):
    plt.figure()
    for i, label in enumerate(class_names):
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_prob[:, i])
        plt.plot(fpr, tpr, label=f"{label} (AUC={auc(fpr, tpr):.2f})")
    plt.plot([0, 1], [0, 1], "k--")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()


# ============================================================
# Run one combination
# ============================================================
def run_one(sensor, scope, data, norm, model_name, aug_root, output_root,
            storage_url, master_rows):
    tag = f"{sensor}_{scope}_{data}_{norm}_{model_name}"
    out_dir = output_root / sensor / scope / data / norm / model_name
    bp_path = out_dir / "best_params.json"
    # Skip if already completed (resume mode)
    if bp_path.exists():
        try:
            with open(bp_path) as f:
                bp = json.load(f)
            row = {
                "sensor": sensor, "scope": scope, "data": data, "norm": norm,
                "model": model_name,
                "cv_acc": bp.get("best_value"),
                "n_trials": bp.get("n_trials"),
                "best_params": json.dumps(bp.get("best_params", {}), ensure_ascii=False),
                "elapsed_sec": 0, "resumed": True,
            }
            # 시도: 이전 test 메트릭 복원 (predictions_test.csv 보면 알 수 있음)
            try:
                pred_df = pd.read_csv(out_dir / "predictions_test.csv")
                row["test_acc"] = float((pred_df["y_true"] == pred_df["y_pred"]).mean())
            except Exception:
                pass
            master_rows.append(row)
            print(f"  SKIP {tag} (already done, cv_acc={row['cv_acc']})")
            return row
        except Exception as e:
            print(f"  WARN: best_params.json read fail, will rerun: {e}")
    print(f"\n=== {tag} ===")
    t0 = time.time()

    # 데이터 로드
    X_train, y_train_raw, X_test, y_test_raw = load_train_test(
        scope, sensor, data, aug_root)

    # SNV / MSC (sample-wise) 적용 — train fit, test transform (data leakage 방지)
    if norm == "snv":
        X_train = apply_snv(X_train)
        X_test = apply_snv(X_test)
    elif norm == "msc":
        X_train, _msc_ref = apply_msc(X_train)
        X_test, _ = apply_msc(X_test, reference=_msc_ref)

    le = LabelEncoder().fit(np.concatenate([y_train_raw, y_test_raw]))
    y_train = le.transform(y_train_raw)
    y_test = le.transform(y_test_raw)
    class_names = le.classes_

    # StandardScaler (feature-wise)
    scaler = StandardScaler().fit(X_train)
    X_train_s = scaler.transform(X_train)
    X_test_s = scaler.transform(X_test)

    y_bin_test = label_binarize(y_test, classes=np.arange(len(class_names)))
    y_bin_train = label_binarize(y_train, classes=np.arange(len(class_names)))

    out_dir = output_root / sensor / scope / data / norm / model_name
    out_dir.mkdir(parents=True, exist_ok=True)

    study = optuna.create_study(
        study_name=tag,
        storage=storage_url,
        load_if_exists=True,
        direction="maximize",
        sampler=TPESampler(seed=RANDOM_STATE),
        pruner=MedianPruner(n_warmup_steps=2),
    )
    study.optimize(
        lambda trial: objective(trial, X_train_s, y_train, model_name),
        n_trials=N_TRIALS,
        show_progress_bar=False,
    )

    trials_df = study.trials_dataframe()
    trials_df.to_csv(out_dir / "optuna_trials.csv", index=False)

    best = {
        "study_name": tag,
        "best_value": study.best_value,
        "best_trial_number": study.best_trial.number,
        "best_params": study.best_params,
        "n_trials": len(study.trials),
        "n_pruned": sum(1 for t in study.trials if t.state.name == "PRUNED"),
    }
    with open(out_dir / "best_params.json", "w") as f:
        json.dump(best, f, indent=2, ensure_ascii=False)

    model = build_final_model(model_name, study.best_params)
    model.fit(X_train_s, y_train)

    y_train_pred = model.predict(X_train_s)
    y_train_prob = model.predict_proba(X_train_s)
    y_test_pred = model.predict(X_test_s)
    y_test_prob = model.predict_proba(X_test_s)

    train_acc = accuracy_score(y_train, y_train_pred)
    train_f1 = f1_score(y_train, y_train_pred, average="macro")
    train_auc = roc_auc_score(y_bin_train, y_train_prob, multi_class="ovr")
    test_acc = accuracy_score(y_test, y_test_pred)
    test_f1 = f1_score(y_test, y_test_pred, average="macro")
    test_auc = roc_auc_score(y_bin_test, y_test_prob, multi_class="ovr")

    save_confusion(y_train, y_train_pred, class_names,
                   out_dir / "confusion_train.png", f"{tag} TRAIN")
    save_confusion(y_test, y_test_pred, class_names,
                   out_dir / "confusion_test.png", f"{tag} TEST")
    save_roc(y_bin_train, y_train_prob, class_names,
             out_dir / "roc_train.png", f"{tag} TRAIN ROC")
    save_roc(y_bin_test, y_test_prob, class_names,
             out_dir / "roc_test.png", f"{tag} TEST ROC")

    pd.DataFrame({
        "y_true": y_test, "y_pred": y_test_pred,
        **{f"prob_{c}": y_test_prob[:, i] for i, c in enumerate(class_names)}
    }).to_csv(out_dir / "predictions_test.csv", index=False)

    elapsed = time.time() - t0
    row = {
        "sensor": sensor, "scope": scope, "data": data, "norm": norm,
        "model": model_name,
        "cv_acc": study.best_value,
        "train_acc": train_acc, "train_f1": train_f1, "train_auc": train_auc,
        "test_acc": test_acc, "test_f1": test_f1, "test_auc": test_auc,
        "n_trials": len(study.trials),
        "n_train": len(y_train), "n_test": len(y_test),
        "elapsed_sec": round(elapsed, 1),
        "best_params": json.dumps(study.best_params, ensure_ascii=False),
    }
    master_rows.append(row)
    print(f"  cv_acc={study.best_value:.4f} test_acc={test_acc:.4f} "
          f"test_f1={test_f1:.4f} ({elapsed:.0f}s)")
    return row


# ============================================================
# Build combination matrix
# ============================================================
def build_combinations(aug_root: Path):
    combos = []
    for sensor in SENSORS:
        for scope in SCOPES:
            for data in DATAS:
                # raw 는 항상 가능, ae/gan은 augmentation CSV 존재 여부 확인
                if data != "raw":
                    try:
                        find_aug_csv(aug_root, sensor, scope, data)
                    except FileNotFoundError:
                        continue  # 해당 augmentation이 없으면 건너뜀
                for norm in NORMS:
                    for model_name in MODELS:
                        combos.append((sensor, scope, data, norm, model_name))
    return combos


# ============================================================
# Main
# ============================================================
def main():
    global N_TRIALS, RANDOM_STATE
    parser = argparse.ArgumentParser()
    parser.add_argument("--sensor", choices=SENSORS)
    parser.add_argument("--scope", choices=SCOPES)
    parser.add_argument("--data", choices=DATAS)
    parser.add_argument("--norm", choices=NORMS)
    parser.add_argument("--model", choices=MODELS)
    parser.add_argument("--n_trials", type=int, default=N_TRIALS)
    parser.add_argument("--seed", type=int, default=42,
                        help="random_state (default 42)")
    parser.add_argument("--out_root_base", type=str, default=None,
                        help="output root (default: <repo>/results/ml)")
    parser.add_argument("--aug_root", type=str, default=None,
                        help="augmentation directory (default: data/augmentation/)")
    parser.add_argument("--out_tag", type=str, default=None,
                        help="output folder suffix (default: timestamp)")
    parser.add_argument("--dry_run", action="store_true")
    args = parser.parse_args()

    N_TRIALS = args.n_trials
    RANDOM_STATE = args.seed
    aug_root = Path(args.aug_root) if args.aug_root else AUG_DIR_DEFAULT

    run_tag = args.out_tag if args.out_tag else datetime.now().strftime("%Y%m%d_%H%M%S")
    out_base = Path(args.out_root_base) if args.out_root_base else (REPO / "results" / "ml")
    output_root = out_base / f"ml_v2_{run_tag}"
    output_root.mkdir(parents=True, exist_ok=True)
    storage_url = f"sqlite:///{output_root}/optuna_studies.db"

    combos = build_combinations(aug_root)
    if args.sensor:
        combos = [c for c in combos if c[0] == args.sensor]
    if args.scope:
        combos = [c for c in combos if c[1] == args.scope]
    if args.data:
        combos = [c for c in combos if c[2] == args.data]
    if args.norm:
        combos = [c for c in combos if c[3] == args.norm]
    if args.model:
        combos = [c for c in combos if c[4] == args.model]

    print(f"\nAug root    : {aug_root}")
    print(f"Output root : {output_root}")
    print(f"Storage     : {storage_url}")
    print(f"Total combos: {len(combos)}")
    print(f"N_trials    : {N_TRIALS}")

    if args.dry_run:
        for c in combos:
            print("  ", c)
        return

    master_rows = []
    t_start = time.time()

    for i, (sensor, scope, data, norm, model_name) in enumerate(combos, 1):
        print(f"\n[{i}/{len(combos)}] sensor={sensor} scope={scope} "
              f"data={data} norm={norm} model={model_name}")
        try:
            run_one(sensor, scope, data, norm, model_name, aug_root,
                    output_root, storage_url, master_rows)
        except Exception as e:
            print(f"  ERROR: {e}")
            master_rows.append({
                "sensor": sensor, "scope": scope, "data": data, "norm": norm,
                "model": model_name, "error": str(e),
            })
        pd.DataFrame(master_rows).to_csv(
            output_root / "master_results.csv", index=False)

    total_elapsed = time.time() - t_start
    print(f"\n=== ALL DONE in {total_elapsed/60:.1f} min ===")
    print(f"Master CSV: {output_root / 'master_results.csv'}")
    print(f"Optuna DB : {storage_url}")


if __name__ == "__main__":
    main()
